[project]
name = "EagleVM"
languages = ["C", "CXX", "ASM_MASM"]

[options]
BUILD_TESTS = false

[conditions]
build-tests = "BUILD_TESTS"

[subdir.deps]

[target.EagleVM]
type = "executable"
include-directories = ["EagleVM/headers"]
sources = [
    "EagleVM/**.cpp",
    "EagleVM/**.h"
]
compile-features = ["cxx_std_23"]
link-libraries = ["EagleVMCore"]

[target.EagleVMCore]
type = "library"
include-directories = ["EagleVM.Core/headers"]
sources = [
    "EagleVM.Core/**.cpp",
    "EagleVM.Core/**.h"
]
compile-features = ["cxx_std_23"]
link-libraries = ["Zydis", "bigint"]
msvc.compile-options = ["/MP", "/permissive-", "/sdl", "/W4", "/Zc:inline", "/Zc:wchar_t", "$<$<CONFIG:Debug>:/FC;/JMC>", "$<$<NOT:$<CONFIG:Debug>>:/Gy;/O1;/Os>"]
msvc.link-options = ["/INCREMENTAL:NO"]

[target.EagleVMStub]
type = "shared"
include-directories = ["EagleVM.Stub/Headers"]
sources = [
    "EagleVM.Stub/**.cpp",
    "EagleVM.Stub/**.h"
]
compile-features = ["cxx_std_23"]

[target.EagleVMSandbox]
type = "executable"
sources = [
    "EagleVM.Sandbox/**.cpp",
    "EagleVM.Sandbox/**.h"
]
compile-features = ["cxx_std_23"]
link-options = ["/DEBUG:FULL"]
link-libraries = ["EagleVMStub"]

[target.EagleVMTests]
type = "executable"
sources = [
    "EagleVM.Tests/source/**.cpp",
    "EagleVM.Tests/headers/**.h",
]
include-directories = ["EagleVM.Tests/headers"]
compile-features = ["cxx_std_23"]
link-libraries = ["EagleVMCore", "nlohmann_json", "Zydis", "spdlog::spdlog", "$<$<BOOL:${MINGW}>:ws2_32>"]
msvc.link-options = ["/DYNAMICBASE:NO"]
