[options]
ZYDIS_BUILD_TOOLS = false
ZYDIS_BUILD_EXAMPLES = false

[subdir.zydis]

[subdir.nlohmann-json]

[subdir.spdlog]

[subdir.linux-pe]

[target.bigint]
type = "interface"
include-directories = ["bigint"]